spring:
  mail:
    host: smtp.gmail.com
    username: farahkhaled648@gmail.com
    password: cadtjnuaphndyyya
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true