
version: "3.8"

services:
  springboot-app:
      container_name: spring-app
      image: springbooot-app
      restart: always
      build: ./ecommerce
      ports:
        - 8090:8090
      environment:
        MYSQL_HOST: mysqldb
        MYSQL_USER: root
        MYSQL_PASSWORD: fhkkn_3072011
        MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      -  ./ecommerce/mysql-data:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ecommers
      MYSQL_ROOT_PASSWORD: fhkkn_3072011

  nodejs_service:
     build: ./React
     container_name: nodejs_service_container
     ports:
       - 3000:3000
     volumes:
       - ./React:/app
       - /app/node_modules